[package]
name = "sidex-cli"
description = "The Sidex command line tool."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "sidex"
path = "src/main.rs"

[dependencies]
# Rust framework for Sidex.
sidex-core.workspace = true
sidex-gen.workspace = true
sidex-gen-ir.workspace = true
sidex-gen-rs.workspace = true
sidex-gen-ts.workspace = true
sidex-gen-json-schema.workspace = true
sidex-gen-py.workspace = true
sidex-diagnostics.workspace = true
sidex-attrs-api.workspace = true
sidex-attrs-validate.workspace = true
sidex-fmt.workspace = true
sidex-fuzz.workspace = true
rand.workspace = true
rand_chacha.workspace = true
# Required for parsing the command line arguments.
clap.workspace = true
# Required for nice and colorful error reporting.
eyre.workspace = true
color-eyre.workspace = true
# Required for terminal colors.
yansi.workspace = true
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
