[package]
name = "sidex-gen-rs"
description = "Sidex code generator for Rust."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dev-dependencies]
sidex-core.workspace = true
sidex-diagnostics.workspace = true
syn = { workspace = true, features = ["full"] }

[dependencies]
# Required for code generation.
sidex-gen.workspace = true # PUBLIC
# Required for parsing `rust` attributes.
sidex-attrs-rust.workspace = true # PUBLIC
# Required for parsing `json` attributes.
sidex-attrs-json.workspace = true # PUBLIC
# Required for parsing `validate` attributes and lowering rules.
sidex-attrs-validate.workspace = true # PUBLIC
sidex-validate-expr.workspace = true # PUBLIC
# Required for parsing `deprecated` / `unstable` / `since` attributes.
sidex-attrs-api.workspace = true # PUBLIC
# Required for generating Rust code.
proc-macro2.workspace = true # PUBLIC
quote.workspace = true # PUBLIC
syn.workspace = true # PUBLIC
# Required for deserializing the backend configuration.
serde.workspace = true # PUBLIC
serde_json.workspace = true

[lints]
workspace = true
