[package]
name = "sidex-serde-tests"
version = "0.0.0"
description = ""
publish = false
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sidex.workspace = true

[build-dependencies]
sidex-build-rs.workspace = true

[lints]
workspace = true
