[package]
name = "sidex"
description = "A format- and language-agnostic data modeling and API definition framework."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
thiserror.workspace = true
sidex-serde.workspace = true
futures = { workspace = true, optional = true }
serde_json.workspace = true
serde.workspace = true

[features]
serde = []

[lints]
workspace = true
