[package]
name = "sidex-gen-py"
description = "Sidex code generation for Python."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dev-dependencies]
sidex-core.workspace = true
sidex-diagnostics.workspace = true
tempfile = "3"

[dependencies]
sidex-gen.workspace = true
sidex-codegen.workspace = true
sidex-attrs-api.workspace = true
sidex-attrs-json.workspace = true
sidex-attrs-py.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
