[package]
name = "sidex-fmt"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
sidex-syntax.workspace = true
sidex-ir.workspace = true
sidex-diagnostics.workspace = true

[dev-dependencies]
insta.workspace = true
