[package]
name = "sidex-fmt"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
sidex-syntax = { path = "../sidex-syntax" }
sidex-ir = { path = "../sidex-ir" }
sidex-diagnostics = { path = "../sidex-diagnostics" }

[dev-dependencies]
insta = { version = "1.21.0", features = ["glob"] }
