[package]
name = "sidex-build-rs"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
sidex-core.workspace = true
sidex-gen.workspace = true
sidex-gen-rs.workspace = true
serde_json.workspace = true
