[package]
name = "sidex-core"
description = "The core of Sidex."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Required for serialization and deserialization of metadata.
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
# Required for nice and colorful error reporting.
eyre.workspace = true # PRIVATE
# Required for caching.
once_cell.workspace = true # PRIVATE
lazy_static.workspace = true # PRIVATE
# Required for internal maps.
hashbrown.workspace = true # PRIVATE
# Lexer, parser, and ASTs for Sidex schemas.
sidex-syntax.workspace = true # PRIVATE
sidex-ir.workspace = true # PUBLIC
sidex-diagnostics.workspace = true # PUBLIC
# Parallel processing of schemas.
rayon.workspace = true # PRIVATE

[dev-dependencies]
# Required for snapshot testing.
insta.workspace = true
