[package]
name = "sidex-gen-ts"
description = "Sidex code generation for TypeScript."
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Required for code generation.
sidex-gen.workspace = true # PUBLIC
sidex-codegen.workspace = true # PUBLIC
# Required for parsing `rust` attributes.
sidex-attrs-rust.workspace = true # PUBLIC
# Required for parsing `json` attributes.
sidex-attrs-json.workspace = true # PUBLIC
# Required for deserializing the backend configuration.
serde.workspace = true # PUBLIC
serde_json.workspace = true
