name: Run Checks

on:
  push:
    branches:
      - main
      - ci
  pull_request:
  workflow_dispatch:

jobs:
  rust-run-tests:
    name: "Rust: Run Tests"
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: cargo test
  
  rust-check-fmt:
    name: "Rust: Check Formatting"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt
      - name: Check Formatting
        run: cargo fmt --all -- --check